#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────
# SRC Advisory — Deployment Workflow Helper
# ─────────────────────────────────────────────────────────────
#
# USAGE:
#   ./scripts/deploy.sh preview    — push current work to dev branch → Vercel preview
#   ./scripts/deploy.sh ship       — merge dev into main → Vercel production
#   ./scripts/deploy.sh status     — show current branch, last commits, preview URL
#   ./scripts/deploy.sh sync       — pull latest main + update dev branch
#
# WORKFLOW:
#   1. Work on dev branch (or a feature branch off dev)
#   2. Push to trigger Vercel preview:  ./scripts/deploy.sh preview
#   3. Test on the preview URL (auto-generated by Vercel)
#   4. When ready, ship to production:   ./scripts/deploy.sh ship
#
set -euo pipefail

BRANCH=$(git branch --show-current)
REMOTE="origin"
MAIN="main"
DEV="dev"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}  →${NC} $1"; }
ok()    { echo -e "${GREEN}  ✓${NC} $1"; }
warn()  { echo -e "${YELLOW}  !${NC} $1"; }
err()   { echo -e "${RED}  ✗${NC} $1"; exit 1; }

# ── PREVIEW: push current branch → trigger Vercel preview ──
cmd_preview() {
    local target="${1:-$DEV}"

    # If on main, refuse
    if [ "$BRANCH" = "$MAIN" ]; then
        err "You are on main. Switch to dev or a feature branch first."
    fi

    # Commit any staged changes
    if ! git diff --cached --quiet; then
        info "Committing staged changes..."
        git commit -m "wip: preview deploy" || true
    fi

    # Check for uncommitted changes
    if ! git diff --quiet || ! git diff --cached --quiet; then
        warn "You have uncommitted/unstaged changes."
        info "Stashing them for the push..."
        git stash push -m "auto-stash before preview"
        STASHED=1
    fi

    info "Pushing ${BRANCH} to ${REMOTE}..."
    git push -u "${REMOTE}" "${BRANCH}"

    # Show preview URL
    local preview_url
    preview_url=$(get_preview_url "$BRANCH")
    if [ -n "$preview_url" ]; then
        echo ""
        ok "Preview deploying: ${CYAN}${preview_url}${NC}"
    else
        echo ""
        ok "Preview deploying — check Vercel dashboard for URL"
    fi

    # Restore stash
    if [ "${STASHED:-0}" = "1" ]; then
        git stash pop 2>/dev/null || true
    fi
}

# ── SHIP: merge dev into main → production deploy ──
cmd_ship() {
    if [ "$BRANCH" = "$MAIN" ]; then
        # Already on main — just push
        info "Pushing main to ${REMOTE}..."
        git push "${REMOTE}" "${MAIN}"
        ok "Production deploying: https://www.src-advisory.ch"
        return
    fi

    # Ensure dev is up to date
    info "Fetching latest..."
    git fetch "${REMOTE}"

    info "Switching to ${MAIN}..."
    git checkout "${MAIN}"
    git pull "${REMOTE}" "${MAIN}"

    info "Merging ${DEV} into ${MAIN}..."
    if git merge "${DEV}" --no-edit; then
        ok "Merge successful"
    else
        err "Merge conflicts — resolve them, then run: ./scripts/deploy.sh ship"
    fi

    info "Pushing ${MAIN} to ${REMOTE}..."
    git push "${REMOTE}" "${MAIN}"

    info "Switching back to ${DEV}..."
    git checkout "${DEV}"

    echo ""
    ok "Production deploying: https://www.src-advisory.ch"
    ok "Preview URL remains active until next push"
}

# ── STATUS: show current state ──
cmd_status() {
    echo -e "${CYAN}SRC Advisory — Deployment Status${NC}"
    echo ""
    echo -e "  Branch:    ${YELLOW}${BRANCH}${NC}"
    echo -e "  Remote:    ${REMOTE}"

    # Latest commits
    echo ""
    echo -e "  ${CYAN}Recent commits on ${BRANCH}:${NC}"
    git log --oneline -5

    # Compare with main
    if [ "$BRANCH" != "$MAIN" ]; then
        local ahead
        ahead=$(git rev-list --count "origin/${MAIN}..${BRANCH}" 2>/dev/null || echo "?")
        echo ""
        echo -e "  Commits ahead of ${MAIN}: ${YELLOW}${ahead}${NC}"

        local preview_url
        preview_url=$(get_preview_url "$BRANCH")
        if [ -n "$preview_url" ]; then
            echo -e "  Preview URL: ${CYAN}${preview_url}${NC}"
        fi
    else
        echo ""
        echo -e "  Production: ${GREEN}https://www.src-advisory.ch${NC}"
    fi
    echo ""
}

# ── SYNC: update dev from main ──
cmd_sync() {
    info "Fetching from ${REMOTE}..."
    git fetch "${REMOTE}"

    if [ "$BRANCH" != "$DEV" ] && [ "$BRANCH" != "$MAIN" ]; then
        # On a feature branch — update dev first, then rebase
        git checkout "${DEV}"
    fi

    if [ "$BRANCH" = "$MAIN" ]; then
        git checkout "${DEV}"
    fi

    info "Updating ${DEV} from ${MAIN}..."
    git pull "${REMOTE}" "${DEV}" || true
    git merge "${REMOTE}/${MAIN}" --no-edit

    info "Pushing updated ${DEV}..."
    git push "${REMOTE}" "${DEV}"

    ok "${DEV} is now up to date with ${MAIN}"
}

# ── Helper: guess Vercel preview URL ──
get_preview_url() {
    local branch="$1"
    local slug
    slug=$(echo "$branch" | sed 's/[^a-zA-Z0-9-]/-/g' | tr '[:upper:]' '[:lower:]' | sed 's/--*/-/g' | sed 's/^-//;s/-$//')
    echo "https://src-website-${slug}.vercel.app"
}

# ── Main ──
case "${1:-status}" in
    preview|pre)
        cmd_preview "${2:-}"
        ;;
    ship|prod|production|deploy)
        cmd_ship
        ;;
    status|st)
        cmd_status
        ;;
    sync|up)
        cmd_sync
        ;;
    *)
        echo "Usage: $0 {preview|ship|status|sync}"
        echo ""
        echo "  preview   Push current branch → Vercel preview deployment"
        echo "  ship      Merge dev into main → production deployment"
        echo "  status    Show branch, commits, and preview URL"
        echo "  sync      Update dev branch with latest main"
        exit 1
        ;;
esac