"""Insert v3 membership keys into i18n.ts at the right places per language block."""
import re

V3 = {
  "en": [
    ("membership.v3.stat1.value", "24/7"),
    ("membership.v3.stat1.label", "Monitoring Cycle"),
    ("membership.v3.stat2.value", "2x"),
    ("membership.v3.stat2.label", "Expert Review"),
    ("membership.v3.stat3.value", "6"),
    ("membership.v3.stat3.label", "Focus Areas"),
    ("membership.v3.essential", "Essential"),
    ("membership.v3.essential.desc", "For professionals who need reliable intelligence and full report access."),
    ("membership.v3.premium", "Premium"),
    ("membership.v3.premium.desc", "For leaders and decision-makers who require early signals, exclusive briefings, and strategic depth."),
    ("membership.v3.expert", "Expert"),
    ("membership.v3.expert.desc", "Tailored pricing for institutions. Direct expert access, bespoke research, and bespoke briefings."),
    ("membership.v3.per-month", "/month"),
    ("membership.v3.billed-annual", "billed annually"),
    ("membership.v3.save-badge", "Save 17%"),
    ("membership.v3.start-trial", "Start Free Trial"),
    ("membership.v3.get-started", "Get Started"),
    ("membership.v3.contact-us", "Contact Us"),
    ("membership.v3.most-popular", "Most Popular"),
    ("membership.v3.studies.tag", "Studies"),
    ("membership.v3.studies.heading", "In-Depth Research"),
    ("membership.v3.studies.desc", "Studies are long-term, comprehensive research projects examining critical topics in depth. Spanning 5,000 to 10,000 words, they combine extensive source analysis, expert validation, and multi-domain perspectives to deliver authoritative assessments."),
    ("membership.v3.studies.read", "Read Study"),
    ("membership.v3.studies.coming-soon", "Coming Soon"),
    ("membership.v3.studies.access-title", "Access all current and upcoming studies"),
    ("membership.v3.studies.access-desc", "Studies are exclusively available to Premium and Custom members. New studies are published quarterly, covering the most critical resilience and security topics across our six focus areas."),
    ("membership.v3.studies.view-plans", "View Membership Plans"),
    ("membership.v3.compare.tag", "Compare"),
    ("membership.v3.compare.heading", "Full Feature Comparison"),
    ("membership.v3.compare.feature", "Feature"),
    ("membership.v3.young.tag", "For the Next Generation"),
    ("membership.v3.young.heading", "Student & Young Professional"),
    ("membership.v3.young.desc", "Under 30? Access all Essential features at a reduced rate. We believe in investing in the next generation of security and resilience leaders."),
    ("membership.v3.young.yp-price", "CHF 190"),
    ("membership.v3.young.yp-label", "Young Professionals (under 30)"),
    ("membership.v3.young.student-price", "CHF 160"),
    ("membership.v3.young.student-label", "Students (with valid enrollment)"),
    ("membership.v3.young.per-year", "/year"),
    ("membership.v3.cta.heading", "Not Sure Which Plan?"),
    ("membership.v3.cta.desc", "Start with a 10-day free trial. Full access to all published reports, opinions, and briefings. No credit card required."),
    ("membership.v3.feat.opinions", "Opinions & Briefs"),
    ("membership.v3.feat.exec-summaries", "Executive Summaries"),
    ("membership.v3.feat.newsletter", "Weekly Newsletter"),
    ("membership.v3.feat.standard-reports", "Standard Reports (2,000\u20134,000 words)"),
    ("membership.v3.feat.daily-brief", "Daily Intelligence Brief"),
    ("membership.v3.feat.pdf", "PDF Downloads"),
    ("membership.v3.feat.archive", "12-Month Archive"),
    ("membership.v3.feat.video", "vAvatar Video Briefings"),
    ("membership.v3.feat.early", "Early Access (24h)"),
    ("membership.v3.feat.forecasts", "Quarterly Forecasts"),
    ("membership.v3.feat.studies", "Studies (long-term research)"),
    ("membership.v3.feat.live-calls", "Live Analyst Calls"),
    ("membership.v3.feat.breaking", "Breaking News Alerts (<4h)"),
    ("membership.v3.feat.summit", "Annual Summit Invitation"),
    ("membership.v3.feat.bespoke", "Bespoke Research Requests"),
    ("membership.v3.feat.account-director", "Dedicated Account Director"),
  ],
  "de": [
    ("membership.v3.stat1.value", "24/7"),
    ("membership.v3.stat1.label", "\u00dcberwachungszyklus"),
    ("membership.v3.stat2.value", "2x"),
    ("membership.v3.stat2.label", "Expertenpr\u00fcfung"),
    ("membership.v3.stat3.value", "6"),
    ("membership.v3.stat3.label", "Schwerpunktbereiche"),
    ("membership.v3.essential", "Essential"),
    ("membership.v3.essential.desc", "F\u00fcr Fachleute, die zuverl\u00e4ssige Intelligence und vollen Berichtszugang ben\u00f6tigen."),
    ("membership.v3.premium", "Premium"),
    ("membership.v3.premium.desc", "F\u00fcr F\u00fchrungskr\u00e4fte und Entscheidungstr\u00e4ger, die fr\u00fchzeitige Signale, exklusive Briefings und strategische Tiefe ben\u00f6tigen."),
    ("membership.v3.expert", "Expert"),
    ("membership.v3.expert.desc", "Massgeschneiderte Preise f\u00fcr Institutionen. Direkter Expertenzugang, ma\u00dfgeschneiderte Forschung und Briefings."),
    ("membership.v3.per-month", "/Monat"),
    ("membership.v3.billed-annual", "j\u00e4hrlich abgerechnet"),
    ("membership.v3.save-badge", "17% sparen"),
    ("membership.v3.start-trial", "Kostenlos testen"),
    ("membership.v3.get-started", "Loslegen"),
    ("membership.v3.contact-us", "Kontaktieren Sie uns"),
    ("membership.v3.most-popular", "Am beliebtesten"),
    ("membership.v3.studies.tag", "Studien"),
    ("membership.v3.studies.heading", "Vertiefte Forschung"),
    ("membership.v3.studies.desc", "Studien sind langfristige, umfassende Forschungsprojekte, die kritische Themen vertieft untersuchen. Sie umfassen 5.000 bis 10.000 W\u00f6rter und kombinieren umfangreiche Quellenanalyse, Expertengutachten und multidisziplin\u00e4re Perspektiven."),
    ("membership.v3.studies.read", "Studie lesen"),
    ("membership.v3.studies.coming-soon", "Demn\u00e4chst"),
    ("membership.v3.studies.access-title", "Zugang zu allen aktuellen und kommenden Studien"),
    ("membership.v3.studies.access-desc", "Studien sind exklusiv f\u00fcr Premium- und Custom-Mitglieder verf\u00fcgbar. Neue Studien werden viertelj\u00e4hrlich ver\u00f6ffentlicht."),
    ("membership.v3.studies.view-plans", "Mitgliedschaftspl\u00e4ne ansehen"),
    ("membership.v3.compare.tag", "Vergleichen"),
    ("membership.v3.compare.heading", "Vollst\u00e4ndiger Funktionsvergleich"),
    ("membership.v3.compare.feature", "Funktion"),
    ("membership.v3.young.tag", "F\u00fcr die n\u00e4chste Generation"),
    ("membership.v3.young.heading", "Student & Young Professional"),
    ("membership.v3.young.desc", "Unter 30? Zugriff auf alle Essential-Funktionen zu einem reduzierten Preis."),
    ("membership.v3.young.yp-price", "CHF 190"),
    ("membership.v3.young.yp-label", "Young Professionals (unter 30)"),
    ("membership.v3.young.student-price", "CHF 160"),
    ("membership.v3.young.student-label", "Studierende (mit g\u00fcltiger Immatrikulation)"),
    ("membership.v3.young.per-year", "/Jahr"),
    ("membership.v3.cta.heading", "Unsicher welcher Plan?"),
    ("membership.v3.cta.desc", "Starten Sie mit einer 10-t\u00e4gigen kostenlosen Testphase. Voller Zugang zu allen ver\u00f6ffentlichten Berichten. Keine Kreditkarte erforderlich."),
    ("membership.v3.feat.opinions", "Meinungen & Kurzberichte"),
    ("membership.v3.feat.exec-summaries", "Managementzusammenfassungen"),
    ("membership.v3.feat.newsletter", "W\u00f6chentlicher Newsletter"),
    ("membership.v3.feat.standard-reports", "Standardberichte (2.000\u20134.000 W\u00f6rter)"),
    ("membership.v3.feat.daily-brief", "T\u00e4glicher Intelligence-Brief"),
    ("membership.v3.feat.pdf", "PDF-Downloads"),
    ("membership.v3.feat.archive", "12-Monate-Archiv"),
    ("membership.v3.feat.video", "vAvatar-Video-Briefings"),
    ("membership.v3.feat.early", "Fr\u00fchzugang (24h)"),
    ("membership.v3.feat.forecasts", "Quartalsprognosen"),
    ("membership.v3.feat.studies", "Studien (langfristige Forschung)"),
    ("membership.v3.feat.live-calls", "Live-Expertenanrufe"),
    ("membership.v3.feat.breaking", "Breaking-News-Alerts (<4h)"),
    ("membership.v3.feat.summit", "Einladung zum Jahresgipfel"),
    ("membership.v3.feat.bespoke", "Ma\u00dfgeschneiderte Forschungsauftr\u00e4ge"),
    ("membership.v3.feat.account-director", "Dedizierter Kundenbetreuer"),
  ],
  "fr": [
    ("membership.v3.stat1.value", "24/7"),
    ("membership.v3.stat1.label", "Cycle de veille"),
    ("membership.v3.stat2.value", "2x"),
    ("membership.v3.stat2.label", "Revue experte"),
    ("membership.v3.stat3.value", "6"),
    ("membership.v3.stat3.label", "Domaines cl\u00e9s"),
    ("membership.v3.essential", "Essentiel"),
    ("membership.v3.essential.desc", "Pour les professionnels qui ont besoin d\u2019analyses fiables et d\u2019un acc\u00e8s complet aux rapports."),
    ("membership.v3.premium", "Premium"),
    ("membership.v3.premium.desc", "Pour les d\u00e9cideurs qui n\u00e9cessitent des signaux anticip\u00e9s, des briefings exclusifs et une profondeur strat\u00e9gique."),
    ("membership.v3.expert", "Expert"),
    ("membership.v3.expert.desc", "Tarifs sur mesure pour les institutions. Acc\u00e8s direct aux experts, recherches personnalis\u00e9es et briefings d\u00e9di\u00e9s."),
    ("membership.v3.per-month", "/mois"),
    ("membership.v3.billed-annual", "facturation annuelle"),
    ("membership.v3.save-badge", "\u00c9conomisez 17%"),
    ("membership.v3.start-trial", "Essai gratuit"),
    ("membership.v3.get-started", "Commencer"),
    ("membership.v3.contact-us", "Nous contacter"),
    ("membership.v3.most-popular", "Le plus populaire"),
    ("membership.v3.studies.tag", "\u00c9tudes"),
    ("membership.v3.studies.heading", "Recherche approfondie"),
    ("membership.v3.studies.desc", "Les \u00e9tudes sont des projets de recherche \u00e0 long terme examinant des sujets critiques en profondeur. Comprendant 5 000 \u00e0 10 000 mots, elles combinent analyse exhaustive des sources, validation experte et perspectives multidisciplinaires."),
    ("membership.v3.studies.read", "Lire l\u2019\u00e9tude"),
    ("membership.v3.studies.coming-soon", "Prochainement"),
    ("membership.v3.studies.access-title", "Acc\u00e9dez \u00e0 toutes les \u00e9tudes actuelles et \u00e0 venir"),
    ("membership.v3.studies.access-desc", "Les \u00e9tudes sont exclusivement disponibles pour les membres Premium et Custom. De nouvelles \u00e9tudes sont publi\u00e9es trimestriellement."),
    ("membership.v3.studies.view-plans", "Voir les formules"),
    ("membership.v3.compare.tag", "Comparer"),
    ("membership.v3.compare.heading", "Comparaison compl\u00e8te des fonctionnalit\u00e9s"),
    ("membership.v3.compare.feature", "Fonctionnalit\u00e9"),
    ("membership.v3.young.tag", "Pour la prochaine g\u00e9n\u00e9ration"),
    ("membership.v3.young.heading", "\u00c9tudiant & Jeune professionnel"),
    ("membership.v3.young.desc", "Moins de 30 ans ? Acc\u00e9dez \u00e0 toutes les fonctionnalit\u00e9s Essentiel \u00e0 tarif r\u00e9duit."),
    ("membership.v3.young.yp-price", "CHF 190"),
    ("membership.v3.young.yp-label", "Jeunes professionnels (moins de 30 ans)"),
    ("membership.v3.young.student-price", "CHF 160"),
    ("membership.v3.young.student-label", "\u00c9tudiants (avec inscription valide)"),
    ("membership.v3.young.per-year", "/an"),
    ("membership.v3.cta.heading", "Pas s\u00fbr de la formule ?"),
    ("membership.v3.cta.desc", "Commencez avec un essai gratuit de 10 jours. Acc\u00e8s complet \u00e0 tous les rapports publi\u00e9s. Sans carte de cr\u00e9dit."),
    ("membership.v3.feat.opinions", "Opinions & Br\u00e8ves"),
    ("membership.v3.feat.exec-summaries", "R\u00e9sum\u00e9s ex\u00e9cutifs"),
    ("membership.v3.feat.newsletter", "Newsletter hebdomadaire"),
    ("membership.v3.feat.standard-reports", "Rapports standards (2 000\u20134 000 mots)"),
    ("membership.v3.feat.daily-brief", "Briefing quotidien"),
    ("membership.v3.feat.pdf", "T\u00e9l\u00e9chargements PDF"),
    ("membership.v3.feat.archive", "Archives 12 mois"),
    ("membership.v3.feat.video", "Briefings vid\u00e9o vAvatar"),
    ("membership.v3.feat.early", "Acc\u00e8s anticip\u00e9 (24h)"),
    ("membership.v3.feat.forecasts", "Pr\u00e9visions trimestrielles"),
    ("membership.v3.feat.studies", "\u00c9tudes (recherche approfondie)"),
    ("membership.v3.feat.live-calls", "Appels analystes en direct"),
    ("membership.v3.feat.breaking", "Alertes flash (<4h)"),
    ("membership.v3.feat.summit", "Invitation au sommet annuel"),
    ("membership.v3.feat.bespoke", "Recherches sur mesure"),
    ("membership.v3.feat.account-director", "Directeur de compte d\u00e9di\u00e9"),
  ],
  "it": [
    ("membership.v3.stat1.value", "24/7"),
    ("membership.v3.stat1.label", "Ciclo di monitoraggio"),
    ("membership.v3.stat2.value", "2x"),
    ("membership.v3.stat2.label", "Revisione esperti"),
    ("membership.v3.stat3.value", "6"),
    ("membership.v3.stat3.label", "Aree di focus"),
    ("membership.v3.essential", "Essential"),
    ("membership.v3.essential.desc", "Per i professionisti che necessitano di intelligence affidabile e accesso completo ai rapporti."),
    ("membership.v3.premium", "Premium"),
    ("membership.v3.premium.desc", "Per i leader che richiedono segnali anticipati, briefings esclusivi e profondit\u00e0 strategica."),
    ("membership.v3.expert", "Expert"),
    ("membership.v3.expert.desc", "Prezzi su misura per le istituzioni. Accesso diretto agli esperti, ricerche personalizzate e briefings dedicati."),
    ("membership.v3.per-month", "/mese"),
    ("membership.v3.billed-annual", "fatturazione annuale"),
    ("membership.v3.save-badge", "Risparmia il 17%"),
    ("membership.v3.start-trial", "Prova gratuita"),
    ("membership.v3.get-started", "Inizia ora"),
    ("membership.v3.contact-us", "Contattaci"),
    ("membership.v3.most-popular", "Pi\u00f9 popolare"),
    ("membership.v3.studies.tag", "Studi"),
    ("membership.v3.studies.heading", "Ricerca approfondita"),
    ("membership.v3.studies.desc", "Gli studi sono progetti di ricerca a lungo termine che esaminano criticit\u00e0 in profondit\u00e0. Da 5.000 a 10.000 parole, combinano analisi esaustiva delle fonti, validazione esperta e prospettive multidisciplinari."),
    ("membership.v3.studies.read", "Leggi lo studio"),
    ("membership.v3.studies.coming-soon", "Prossimamente"),
    ("membership.v3.studies.access-title", "Accedi a tutti gli studi attuali e in arrivo"),
    ("membership.v3.studies.access-desc", "Gli studi sono esclusivamente disponibili per i membri Premium e Custom. Nuovi studi vengono pubblicati trimestralmente."),
    ("membership.v3.studies.view-plans", "Vedi i piani"),
    ("membership.v3.compare.tag", "Confronta"),
    ("membership.v3.compare.heading", "Confronto completo delle funzionalit\u00e0"),
    ("membership.v3.compare.feature", "Funzionalit\u00e0"),
    ("membership.v3.young.tag", "Per la prossima generazione"),
    ("membership.v3.young.heading", "Studente & Giovane professionista"),
    ("membership.v3.young.desc", "Sotto i 30 anni? Accesso a tutte le funzionalit\u00e0 Essential a tariffa ridotta."),
    ("membership.v3.young.yp-price", "CHF 190"),
    ("membership.v3.young.yp-label", "Giovani professionisti (sotto i 30)"),
    ("membership.v3.young.student-price", "CHF 160"),
    ("membership.v3.young.student-label", "Studenti (con iscrizione valida)"),
    ("membership.v3.young.per-year", "/anno"),
    ("membership.v3.cta.heading", "Non sai quale piano scegliere?"),
    ("membership.v3.cta.desc", "Inizia con una prova gratuita di 10 giorni. Accesso completo a tutti i rapporti pubblicati. Nessuna carta di credito richiesta."),
    ("membership.v3.feat.opinions", "Opinioni & Brief"),
    ("membership.v3.feat.exec-summaries", "Riassunti esecutivi"),
    ("membership.v3.feat.newsletter", "Newsletter settimanale"),
    ("membership.v3.feat.standard-reports", "Rapporti standard (2.000\u20134.000 parole)"),
    ("membership.v3.feat.daily-brief", "Briefing giornaliero"),
    ("membership.v3.feat.pdf", "Download PDF"),
    ("membership.v3.feat.archive", "Archivio 12 mesi"),
    ("membership.v3.feat.video", "Briefing video vAvatar"),
    ("membership.v3.feat.early", "Accesso anticipato (24h)"),
    ("membership.v3.feat.forecasts", "Previsioni trimestrali"),
    ("membership.v3.feat.studies", "Studi (ricerca approfondita)"),
    ("membership.v3.feat.live-calls", "Chiamate analisti in diretta"),
    ("membership.v3.feat.breaking", "Alert breaking news (<4h)"),
    ("membership.v3.feat.summit", "Invito al summit annuale"),
    ("membership.v3.feat.bespoke", "Ricerche personalizzate"),
    ("membership.v3.feat.account-director", "Account manager dedicato"),
  ],
}

# Find the last membership.journey.s4.desc line in each language block and insert after it
# The language blocks start with: en: {, de: {, fr: {, it: {
# We find the insertion points by looking for the pattern

with open("src/lib/i18n.ts", "r") as f:
    content = f.read()

lines = content.split("\n")
# Find line indices (0-based) of last membership.journey.s4.desc per language
# EN: around line 341, DE: around 773, FR: around 1205, IT: around 1637
insert_points = {}
lang_line_ranges = {"en": (0, 450), "de": (450, 900), "fr": (900, 1350), "it": (1350, 1800)}

for lang, (start, end) in lang_line_ranges.items():
    last_journey = -1
    for i in range(start, min(end, len(lines))):
        if "membership.journey.s4.desc" in lines[i]:
            last_journey = i
    if last_journey >= 0:
        insert_points[lang] = last_journey
    else:
        print(f"WARNING: Could not find journey.s4.desc for {lang}")

# Build new lines to insert per language (in reverse order so indices stay valid)
for lang in ["it", "fr", "de", "en"]:
    idx = insert_points[lang]
    keys = V3[lang]
    insert_text = "\n".join(f'    "{k}": "{v}",' for k, v in keys)
    lines.insert(idx + 1, insert_text)

with open("src/lib/i18n.ts", "w") as f:
    f.write("\n".join(lines))

print(f"Inserted {sum(len(v) for v in V3.values())} v3 keys into i18n.ts")